# Generated by Django 6.0.3 on 2026-03-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_date_member_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date',
            new_name='phone',
        ),
    ]
