# Generated by Django 6.0.3 on 2026-03-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
