# Generated by Django 6.0.3 on 2026-04-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
